### ISSUE TITLE
race condition in tests

### ISSUE THREAD

**Issue by kornel661** [braintree/manners#15]
It seems to me that line 40
```
<-done
```
should be moved to the end of the function to avoid a race condition between:

* the server shutting down (and assignment ```exited=true```) and
* the check ```if exited {...```

I'm aware that this test runs only on one thread and the handler takes quite long to complete (so the race is highly unlikely), but I believe that the Go memory model makes this change mandatory (to get correct, predictable results according to the language semantics).

Another race is in the ```TestShutdown```. Concurrent execution may lead to a situation where the server is still running but the other goroutine went ahead and successfully connected.

**Comment by lionelbarrow** [comment]
This has been fixed as part of the rewrite.
