### ISSUE TITLE
Please merge non-backwards-compat

### ISSUE THREAD

**Issue by FiloSottile** [braintree/manners#26]
I've been reviewing the non-backwards-compat branch, and it looks like the perfect implementation of a no-timeout graceful-stopping http.Server. Is there anything stopping it from becoming master?

Thanks for the work!

**Comment by lionelbarrow** [comment]
I've been chipping away at trying to merge it off and on. My main issue is that I want to rewrite the tests to be easier to understand, and it makes some changes to the API that I'm not sure about.

I suppose I can merge it in and then rewrite the tests later. I'll look into that over the weekend.

**Comment by lionelbarrow** [comment]
Merge. I'm going to spend some time refactoring the tests.
