### ISSUE TITLE
TestShutdown intermittently fails

### ISSUE THREAD

**Issue by FiloSottile** [braintree/manners#27]
Go 1.4.2 - non-b... branch

```
--- FAIL: TestShutdown (0.00s)
	server_test.go:64: Waitcount should be one, got 0
```

**Comment by FiloSottile** [comment]
Here is a probably related error

```
--- FAIL: TestGracefulness (0.00s)
	server_test.go:30: Expected the waitgroup to equal 1 at shutdown; actually 0
```

**Comment by FiloSottile** [comment]
The problem is that StartRoutine has not yet been called.

**Comment by FiloSottile** [comment]
A stronger way to ensure that the connection entered the new state is needed. Making the handler block instead might be an option.

**Comment by lionelbarrow** [comment]
Thanks for fixing this. https://github.com/braintree/manners/pull/29 is merged now so I'll close the issue.
